version: '3'

includes:
  frontend:
    dir: ./frontend
    taskfile: ./frontend/Taskfile.yml
    aliases:
      - fe
      
  backend:
    dir: ./backend
    taskfile: ./backend/Taskfile.yml
    aliases:
      - be

tasks:
  default:
    desc: Show commands
    cmds:
      - task -a --sort none
