linters-settings:
  goimports:
    local-prefixes: github.com/keito-isurugi/next-go-project
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - revive
    - govet
    - goimports
    - gocyclo
    - misspell
    - unparam
    - nakedret
    - gosec
    - gocognit
    - goconst
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - whitespace

# issues:
#   exclude-dirs:
#     - internal/domain/repository/mock
#     - internal/domain/repository/bigadvance/mock
#     - swagger
#   exclude-rules:
#     # NOTE: testファイルでの定数定義のエラーは適応させない
#     - path: _test\.go
#       linters:
#         - goconst
#     # TODO 循環的複雑度が(> 15)なので要リファクタ
#     # - path: internal\/usecase\/appointment\/get_availabilities_usecase\.go
#     #   linters:
#     #     - gocyclo
#     # TODO 循環的複雑度が(> 30)なので要リファクタ
#     - path: internal\/server\/middleware\/logger\.go
#       linters:
#         - gocyclo