version: '3'

tasks:
  exec-schema:
    desc: Create schema for test DB
    cmds:
      - cat ./DDL/*.up.sql > ./DDL/schema.sql
      - docker cp ./DDL/schema.sql next-go-project-db:/ && docker exec -it next-go-project-db psql -U postgres -d next_go -f /schema.sql
      - docker cp ./DDL/schema.sql next-go-project-db-test:/ && docker exec -it next-go-project-db-test psql -U test -d next_go_test -f /schema.sql
      - rm ./DDL/schema.sql

  exec-dummy:
    desc: Insert dummy data for test DB
    cmds:
      - docker cp DDL/insert_dummy_data.sql db:/ && docker exec -it db psql -U postgres -d next_go -f /insert_dummy_data.sqlPP